# Generated by Django 6.0.4 on 2026-04-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Programming', 'Programming'), ('Cloud Computing', 'Cloud Computing'), ('Cyber Security', 'Cyber Security'), ('Engineering', 'Engineering'), ('Science & Research', 'Science & Research'), ('Business', 'Business')], max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='')),
                ('duration', models.CharField(default='3 months', max_length=50)),
                ('instructor', models.CharField(default='Expert Instructor', max_length=100)),
                ('topics', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('IT Jobs', 'IT Jobs'), ('Data Science', 'Data Science'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('HR', 'HR'), ('Engineering', 'Engineering'), ('Design', 'Design')], max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('posted_days_ago', models.IntegerField(default=1)),
                ('apply_url', models.URLField(blank=True, default='#')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
